CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(512) NOT NULL UNIQUE,
    password VARCHAR(512) NOT NULL,
    secret VARCHAR(512) UNIQUE,
    flags INTEGER NOT NULL
);
